server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'
    
logging:
  level:
    org:
      zalando:
        logbook: TRACE
#      springframework:
#        security: trace
       
logbook:
  format:
    style: http
  minimum-status: 200